# Generated by Django 4.1.2 on 2022-11-15 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Btech19', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parents',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Btech19.category'),
        ),
    ]
