# Generated by Django 4.1.2 on 2022-11-15 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Btech19', '0002_category_parents'),
    ]

    operations = [
        migrations.CreateModel(
            name='PodCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parents', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Btech19.category')),
            ],
        ),
    ]
