# Generated by Django 4.1.3 on 2022-11-11 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_popular', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Btech19.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('price', models.FloatField(blank=True, max_length=20, null=True, verbose_name='цена')),
                ('cpu', models.CharField(max_length=50, null=True)),
                ('main_camera', models.CharField(blank=True, max_length=50, null=True, verbose_name='основная камера')),
                ('front_camera', models.CharField(blank=True, max_length=50, null=True, verbose_name='фронтальная камера')),
                ('memory', models.PositiveIntegerField(null=True, verbose_name='память')),
                ('ram', models.PositiveIntegerField(null=True, verbose_name='оперативная память')),
                ('is_active', models.BooleanField(default=True)),
                ('is_hit', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Btech19.category')),
            ],
        ),
        migrations.CreateModel(
            name='ImageProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Btech19.product')),
            ],
        ),
    ]
