# Generated by Django 4.1.3 on 2022-11-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Btech19', '0002_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
    ]
