# Generated by Django 4.1.3 on 2022-11-09 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Btech19', '0003_alter_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='text',
            new_name='installment',
        ),
    ]
