# Generated by Django 4.1.3 on 2022-11-09 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Btech19', '0004_rename_text_product_installment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='product_name',
        ),
    ]
