# Generated by Django 4.1.3 on 2022-11-09 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Btech19', '0006_product_image_imageproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_active',
        ),
        migrations.AddField(
            model_name='product',
            name='cpu',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='front_camera',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='main_camera',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='memory',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ram',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
